services:
  proxy:
    image: ghcr.io/prismmarketlabs/proxy:0.1.25
    restart: always
    ports:
      - "8090:8090"
      - "9901:9901"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: "{{.Name}}"
    environment:
      ENVOY_HOST_CLOB: ${ENVOY_HOST_CLOB}
      ENVOY_HOST_API: ${ENVOY_HOST_API}
      ENVOY_HOST_WEB: ${ENVOY_HOST_WEB}
      ENVOY_HOST_WEB_ADMIN: ${ENVOY_HOST_WEB_ADMIN}
      ENVOY_HOST_WEB_LP: ${ENVOY_HOST_WEB_LP}
