services:
  api:
    image: ghcr.io/prismmarketlabs/api:0.6.39
    restart: always
    ports:
      - "8888:8888"
      - "8889:8889"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: "{{.Name}}"
    environment:
      API_SELF_HOST: ${API_SELF_HOST}
      API_SELF_PORT: ${API_SELF_PORT}
      API_SELF_PORT_HEALTH: ${API_SELF_PORT_HEALTH}
      CLOB_HOST: ${CLOB_HOST}
      CLOB_PORT: ${CLOB_PORT}
      USDC_DECIMALS: ${USDC_DECIMALS}
      PREVIEWNET_USDC_ADDRESS: ${PREVIEWNET_USDC_ADDRESS}
      TESTNET_USDC_ADDRESS: ${TESTNET_USDC_ADDRESS}
      MAINNET_USDC_ADDRESS: ${MAINNET_USDC_ADDRESS}
      AVAILABLE_NETWORKS: ${AVAILABLE_NETWORKS}
      AVAILABLE_NETWORKS_ADMIN: ${AVAILABLE_NETWORKS_ADMIN}
      PREVIEWNET_SMART_CONTRACT_ID: ${PREVIEWNET_SMART_CONTRACT_ID}
      PREVIEWNET_HCS_TOPIC_ID: ${PREVIEWNET_HCS_TOPIC_ID}
      PREVIEWNET_HEDERA_OPERATOR_ID: ${PREVIEWNET_HEDERA_OPERATOR_ID}
      PREVIEWNET_HEDERA_OPERATOR_KEY_TYPE: ${PREVIEWNET_HEDERA_OPERATOR_KEY_TYPE}
      PREVIEWNET_PUBLIC_KEY: ${PREVIEWNET_PUBLIC_KEY}
      TESTNET_SMART_CONTRACT_ID: ${TESTNET_SMART_CONTRACT_ID}
      TESTNET_HCS_TOPIC_ID: ${TESTNET_HCS_TOPIC_ID}
      TESTNET_HEDERA_OPERATOR_KEY_TYPE: ${TESTNET_HEDERA_OPERATOR_KEY_TYPE}
      TESTNET_HEDERA_OPERATOR_ID: ${TESTNET_HEDERA_OPERATOR_ID}
      TESTNET_PUBLIC_KEY: ${TESTNET_PUBLIC_KEY}
      MAINNET_SMART_CONTRACT_ID: ${MAINNET_SMART_CONTRACT_ID}
      MAINNET_HCS_TOPIC_ID: ${MAINNET_HCS_TOPIC_ID}
      MAINNET_HEDERA_OPERATOR_ID: ${MAINNET_HEDERA_OPERATOR_ID}
      MAINNET_HEDERA_OPERATOR_KEY_TYPE: ${MAINNET_HEDERA_OPERATOR_KEY_TYPE}
      MAINNET_PUBLIC_KEY: ${MAINNET_PUBLIC_KEY}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_UNAME: ${DB_UNAME}
      DB_NAME: ${DB_NAME}
      DB_MAX_ROWS: ${DB_MAX_ROWS}
      NATS_URL: ${NATS_URL}
      TIMESTAMP_ALLOWED_PAST_SECONDS: ${TIMESTAMP_ALLOWED_PAST_SECONDS}
      TIMESTAMP_ALLOWED_FUTURE_SECONDS: ${TIMESTAMP_ALLOWED_FUTURE_SECONDS}
      SEND_EMAIL: ${SEND_EMAIL}
      EMAIL_ADDRESS: ${EMAIL_ADDRESS}
      SMTP_ENDPOINT: ${SMTP_ENDPOINT}
      IAM_USERNAME: ${IAM_USERNAME}
      SMTP_USERNAME: ${SMTP_USERNAME}
      MARKET_CREATION_FEE_USDC: ${MARKET_CREATION_FEE_USDC}
      TOKEN_DECIMALS: ${TOKEN_DECIMALS}
      PREVIEWNET_TOKEN: ${PREVIEWNET_TOKEN}
      TESTNET_TOKEN: ${TESTNET_TOKEN}
      MAINNET_TOKEN: ${MAINNET_TOKEN}
      MIN_ORDER_SIZE_USD: ${MIN_ORDER_SIZE_USD}
      CRON_STR_KICK_UNFUNDED: ${CRON_STR_KICK_UNFUNDED}
      CRON_STR_LOM: ${CRON_STR_LOM}
      JWT_EXPIRY_HOURS: ${JWT_EXPIRY_HOURS}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      S3_AWS_REGION: ${S3_AWS_REGION}
      OPENAI_API_BASE_URL: ${OPENAI_API_BASE_URL}
      DB_PWORD: ${DB_PWORD}
      PREVIEWNET_HEDERA_OPERATOR_KEY: ${PREVIEWNET_HEDERA_OPERATOR_KEY}
      TESTNET_HEDERA_OPERATOR_KEY: ${TESTNET_HEDERA_OPERATOR_KEY}
      MAINNET_HEDERA_OPERATOR_KEY: ${MAINNET_HEDERA_OPERATOR_KEY}
      SMTP_PWORD: ${SMTP_PWORD}
      JWT_SECRET: ${JWT_SECRET}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
  clob:
    image: ghcr.io/prismmarketlabs/clob:0.3.9
    restart: always
    depends_on:
      - api
    ports:
      - "50051:50051"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: "{{.Name}}"
    environment:
      CLOB_SELF_HOST: ${CLOB_SELF_HOST}
      CLOB_SELF_PORT: ${CLOB_SELF_PORT}
      API_HOST: ${API_HOST}
      API_PORT: ${API_PORT}
      CLOB_MATCHING_INTERVAL_SECONDS: ${CLOB_MATCHING_INTERVAL_SECONDS}
      NATS_HOST: ${NATS_HOST}
      NATS_PORT: ${NATS_PORT}
  web:
    image: ghcr.io/prismmarketlabs/web:0.8.14
    restart: always
    ports:
      - "5173:80"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: "{{.Name}}"
    environment:
      IS_PASSWORD_PROTECTED: ${IS_PASSWORD_PROTECTED}
      HTUSER: ${HTUSER}
      HTPASSWD: ${HTPASSWD}
      ROBOTS_TAG_VALUE: ${ROBOTS_TAG_VALUE}
  web.admin:
    image: ghcr.io/prismmarketlabs/web.admin:0.2.6
    restart: always
    ports:
      - "8080:80"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: "{{.Name}}"
    environment:
      WEB_ADMIN_IS_PASSWORD_PROTECTED: ${WEB_ADMIN_IS_PASSWORD_PROTECTED}
      WEB_ADMIN_HTUSER: ${WEB_ADMIN_HTUSER}
      WEB_ADMIN_HTPASSWD: ${WEB_ADMIN_HTPASSWD}
  web.lp:
    image: ghcr.io/prismmarketlabs/web.lp:0.4.8
    restart: always
    ports:
      - "8081:80"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: "{{.Name}}"
    environment:
      WEB_LP_IS_PASSWORD_PROTECTED: ${WEB_LP_IS_PASSWORD_PROTECTED}
      WEB_LP_HTUSER: ${WEB_LP_HTUSER}
      WEB_LP_HTPASSWD: ${WEB_LP_HTPASSWD}
