services:
  proxy:
    image: ghcr.io/prismmarketlabs/proxy:0.1.27
    restart: always
    ports:
      - "9901:9901"
    expose:
      - "8090"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: "{{.Name}}"
    environment:
      ENVOY_HOST_CLOB: ${ENVOY_HOST_CLOB}
      ENVOY_HOST_API: ${ENVOY_HOST_API}
      ENVOY_HOST_WEB: ${ENVOY_HOST_WEB}
      ENVOY_HOST_WEB_ADMIN: ${ENVOY_HOST_WEB_ADMIN}
      ENVOY_HOST_WEB_LP: ${ENVOY_HOST_WEB_LP}
  modsec:
    image: ghcr.io/prismmarketlabs/modsec:0.0.3
    restart: unless-stopped
    ports:
      - "8090:8080"
    depends_on:
      - proxy
    environment:
      - BACKEND=${MODSEC_BACKEND}
      - PARANOIA=${MODSEC_PARANOIA}
      - ANOMALY_INBOUND=${MODSEC_ANOMALY_INBOUND}
      - ANOMALY_OUTBOUND=${MODSEC_ANOMALY_OUTBOUND}
