services:
  api:
    image: ghcr.io/prismmarketlabs/api:0.4.10
  clob:
    image: ghcr.io/prismmarketlabs/clob:0.2.14
  web:
    image: ghcr.io/prismmarketlabs/web:0.6.31
  web.admin:
    image: ghcr.io/prismmarketlabs/web.admin:0.1.10
  web.lp:
    image: ghcr.io/prismmarketlabs/web.lp:0.4.5
 