services:
  db:
    image: ghcr.io/prismmarketlabs/db:0.1.3
    restart: always
    volumes:
      - /mnt/external/postgresdata:/var/lib/postgresql
    ports:
      - "5432:5432"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: "{{.Name}}"
    environment:
      POSTGRES_USER: ${DB_UNAME}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PWORD}
  eventbus:
    image: ghcr.io/prismmarketlabs/eventbus:0.1.5
    restart: always
    ports:
      - "4222:4222"
      - "6222:6222"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: "{{.Name}}"
  redis:
    image: ghcr.io/prismmarketlabs/redis:0.0.1
    restart: always
    ports:
      - "6379:6379"
  blocknode:
    image: ghcr.io/prismmarketlabs/blocknode:0.1.15
    restart: always
    ports:
      - "7777:7777"
    environment:
      BN_QUERY_FREQ_SECS: ${BN_QUERY_FREQ_SECS}
      BN_QUERY_LOOKBACK_SECS: ${BN_QUERY_LOOKBACK_SECS}
      BN_SUPPORTED_NETWORKS: "${BN_SUPPORTED_NETWORKS}"
      BN_NATS_HOST: ${BN_NATS_HOST}
      BN_NATS_PORT: ${BN_NATS_PORT}
      BN_SMART_CONTRACT_IDS_PREVIEWNET: "${BN_SMART_CONTRACT_IDS_PREVIEWNET}"
      BN_SMART_CONTRACT_IDS_TESTNET: "${BN_SMART_CONTRACT_IDS_TESTNET}"
      BN_SMART_CONTRACT_IDS_MAINNET: "${BN_SMART_CONTRACT_IDS_MAINNET}"
      ABI_TESTNET_0_0_8946970: "${ABI_TESTNET_0_0_8946970}"
      ABI_TESTNET_0_0_8947052: "${ABI_TESTNET_0_0_8947052}"
      ABI_TESTNET_0_0_9070333: "${ABI_TESTNET_0_0_9070333}"
      ABI_TESTNET_0_0_9159758: "${ABI_TESTNET_0_0_9159758}"
      ABI_TESTNET_0_0_9167018: "${ABI_TESTNET_0_0_9167018}"
      ABI_TESTNET_0_0_9214025: "${ABI_TESTNET_0_0_9214025}"
      ABI_TESTNET_0_0_9385460: "${ABI_TESTNET_0_0_9385460}"
      ABI_TESTNET_0_0_9458377: "${ABI_TESTNET_0_0_9458377}"
      ABI_TESTNET_0_0_9502269: "${ABI_TESTNET_0_0_9502269}"
      ABI_TESTNET_0_0_9653861: "${ABI_TESTNET_0_0_9653861}"
      ABI_TESTNET_0_0_9792499: "${ABI_TESTNET_0_0_9792499}"
