syntax = "proto3";

package clob;
option go_package = "clob/gen;clob"; // Golang requires this!

import "validate/validate.proto"; // PGV

// intentionally separating public and internal services for clarity and security (espcially when using Envoy proxy)
service ClobPublic {
  rpc Health(Empty) returns (StdResponse);
  rpc GetBook (BookRequest) returns (BookSnapshot);
  rpc StreamBook (BookRequest) returns (stream BookSnapshot);
  rpc GetPrice (MarketIdRequest) returns (PriceUpdate);
  rpc StreamPrice (MarketIdRequest) returns (stream PriceUpdate);
}

service ClobInternal {
  rpc CreateOrder (CreateOrderRequestClob) returns (StdResponse);
  rpc CreateMarket (CreateMarketRequest) returns (StdResponse);
  rpc CloseMarket (MarketIdRequest) returns (StdResponse);

  rpc CancelOrder(CancelOrderRequest) returns (StdResponse);
  rpc GetOrdersForUser(UserRequest) returns (OrdersForUserResponse);
  // rpc PauseMarketToggle (MarketIdRequest) returns (StdResponse);
  // rpc DeleteMarket(MarketIdRequest) returns (StdResponse); // nuke the market on the CLOB
  rpc GetTvPendingUsd(Empty) returns (StdResponse);
  rpc GetMarketDepthQty(MarketIdRequest) returns (MarketDepthQtyResponse);
}

message Empty {}

// Note: ensure there's a persistent record of all the values here - need to be able to re-create the CLOB state from these values alone
message CreateOrderRequestClob {
  string tx_id = 1 [json_name = "txId", (validate.rules).string = {pattern: "(?i)^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"} /* Strict RFC-9562-compliant UUIDv7 */];
  string net = 2 [json_name = "net"];
  string market_id = 3 [json_name = "marketId"];
  string account_id = 4 [json_name = "accountId"];
  double price_usd = 5 [json_name = "priceUsd"];
  double qty = 6 [json_name = "qty"];
  double qty_orig = 7 [json_name = "qtyOrig"]; // keep track of the original qty for signature validation
  string sig = 8 [json_name = "sig"];
  string public_key = 9 [json_name = "publicKey"]; // pass key info - i) avoid lookups ii) handle situation where user has changed their key
  string evm_address = 10 [json_name = "evmAddress"];
  int32 key_type = 11 [json_name = "keyType"];
  string primary_secondary = 12 [json_name = "primarySecondary", (validate.rules).string = {in: ["p", "s"]}];
  // double leverage = 13 [json_name = "leverage", (validate.rules).double = {gte: 1.0, lte: 100.0}];
}

message StdResponse {
  string message = 1     [json_name = "message"];
  int32 error_code = 2   [json_name = "errorCode"];
}

message BookRequest {
  string market_id = 1 [json_name = "marketId",    (validate.rules).string = {pattern: "(?i)^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"} /* Strict RFC-9562-compliant UUIDv7 */];
  uint32 depth = 2     [json_name = "depth",       (validate.rules).uint32 = {gt: 0, lt: 1000}];
}

message OrderDetail {
  string tx_id = 1      [json_name = "txId"];
  string account_id = 2 [json_name = "accountId"];
  double price_usd = 3  [json_name = "priceUsd"];
  double qty = 4        [json_name = "qty"];
  string ps = 5         [json_name = "ps", (validate.rules).string = {in: ["p", "s"]}];
}

message BookSnapshot {
  repeated OrderDetail bids = 1;
  repeated OrderDetail asks = 2;
}


message CreateMarketRequest {
  string market_id = 1    [json_name = "marketId",    (validate.rules).string = {pattern: "(?i)^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"} /* Strict RFC-9562-compliant UUIDv7 */];
}

message MarketIdRequest {
  string market_id = 1    [json_name = "marketId",    (validate.rules).string = {pattern: "(?i)^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"} /* Strict RFC-9562-compliant UUIDv7 */];
}

message PriceUpdate {  // want [timestampMs[], priceUsdBid[], priceUsdAsk[]] for graphing (e.g. uplot)
  double price_bid_usd = 1    [json_name = "priceBidUsd"];
  double price_ask_usd = 2    [json_name = "priceAskUsd"];
  int64 timestamp_ms = 3      [json_name = "timestampMs"];
}

message CancelOrderRequest {
  string market_id = 1    [json_name = "marketId",    (validate.rules).string = {pattern: "(?i)^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"} /* Strict RFC-9562-compliant UUIDv7 */];
  string tx_id = 2        [json_name = "txId",        (validate.rules).string = {pattern: "(?i)^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"} /* Strict RFC-9562-compliant UUIDv7 */];
}

message UserRequest {
  string evm_address = 1  [json_name = "evmAddress", (validate.rules).string = {pattern: "(?i)^0x[a-f0-9]{40}$"} /* Ethereum address */];
}

message OrdersForUserResponse {
  repeated CreateOrderRequestClob open_orders = 1;
}

message MarketDepthQtyResponse {
  double qty_bid = 1 [json_name = "qtyBid"];
  double qty_ask = 2 [json_name = "qtyAsk"];
}
